version: "3"

services:

  database:
    container_name: springboot-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kspir
      POSTGRES_PASSWORD: secure123!
      POSTGRES_DB: springboot
    networks:
      main:
        ipv4_address: 172.18.1.4

  nginx:
    container_name: nginx-connector
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      main:
        ipv4_address: 172.18.1.10


  redis:
    container_name: redis-springboot-cache
    image: redis:latest
    command:
      - /bin/sh
      - -c
      - redis-server --appendonly yes --requirepass "secure123!"
    ports:
      - "6379:6379"
    networks:
      redis:
        ipv4_address: 172.19.1.10

  backend:
    container_name: backend-server
    build: .
    ports:
      - "8080:8080"
    networks:
      main:
        ipv4_address: 172.18.1.2
      redis:
        ipv4_address: 172.19.1.6
    depends_on:
      - database
      - redis



networks:
  main:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
  redis:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24